version: "2.4"

x-db-config: &db-config
  POSTGRES_PASSWORD: test
  POSTGRES_DB: eas

services:
  db:
    image: postgres
    restart: always
    hostname: postgres
    healthcheck:
      test: pg_isready
    environment: *db-config
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d