version: "2.4"

x-db-config: &db-config
  POSTGRES_PASSWORD: test
  POSTGRES_DB: eas

services:
  db:
    image: postgres
    restart: always
    hostname: postgres
    healthcheck:
      test: pg_isready
    environment: *db-config
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  api:
    build:
      context: ./postgres
      dockerfile: postgraphile.dockerfile
    restart: always
    ports:
      - 45000:5000
    command: --connection postgres://postgraphile:ari@db/eas --schema public --default-role anonymous --secret keyboard_kitten --token public.jwt_token --enhance-graphiql --append-plugins @graphile-contrib/pg-simplify-inflector --simple-collections only -o
    depends_on:
      db:
        condition: service_healthy